services:
  postgres:
    image: postgres:17
    container_name: avito-queue-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: avito_queue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d avito_queue"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: ghcr.io/kukymbr/goose-docker:latest
    container_name: avito-queue-migrator
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations:ro
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: host=postgres port=5432 user=postgres password=postgres dbname=avito_queue sslmode=disable

volumes:
  postgres_data: