services:
  postgres:
    image: postgres:17
    container_name: avito-queue-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: avito_queue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d avito_queue"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: ghcr.io/kukymbr/goose-docker:latest
    container_name: avito-queue-migrator
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations:ro
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: host=postgres port=5432 user=postgres password=postgres dbname=avito_queue sslmode=disable

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito-queue-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: avito_queue
      CONFIG_PATH: "configs/configuration.yaml"
    volumes:
      - ./configs:/app/configs
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
  
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: avito-queue-frontend
    restart: unless-stopped
    ports:
      - "3000:80" 
    depends_on:
      - app 

volumes:
  postgres_data: