# slog levels: -4 debug, 0 info, 4 warn, 8 error
Logger:
  Level: 0

http_server:
  host: "localhost"
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "avito"
  password: "avito"
  name: "avito_queue"
  sslmode: "disable"