# slog levels: -4 debug, 0 info, 4 warn, 8 error
logger:
  level: 0

http_server:
  host: "0.0.0.0"
  port: 8080

auth:
  session_secret: "super-secret-key-for-avito-queue"

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: avito_queue
  ssl_mode: disable